# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
with open("/home/rithvik/House_pricing/House_Price_Prediction", "rb") as f:
    model = pickle.load(f)

def get_prediction(Neighborhood, HouseStyle, MSZoning, GrLivArea, TotalBsmtSF, GarageType, OverallQual, Utilities):

   
    ngbs = ['Bloomington Heights', 'Bluestem', 'Briardale', 'Brookside', 'Clear Creek', 'College Creek', 'Crawford', 'Edwards', 'Gilbert', 'Iowa DOT and Rail Road', 'Meadow Village', 'Mitchell', 'North Ames','Northpark Villa','Northwest Ames', 'Northridge', 'Northridge Heights', 'Old Town', 'South & West of Iowa State University', 'Sawyer', 'Sawyer West', 'Somerset', 'Stone Brook', 'Timberland', 'Veenker']
    ngb_lblEval = {}
    for i in range(25):
        ngb_lblEval[ngbs[i]] = i
        
    MSZ = {'C (all)':0, 'FV':1, 'RH':2, 'RL':3, 'RM':4}
    Utili = {'AllPub':0, 'NoSeWa':1}
    Hstyle = {'1.5Fin':0, '1.5Unf':1, '1Story':2, '2.5Fin':3, '2.5Unf':4, '2Story':5, 'SFoyer':6, 'SLvl':7}
    grgtype = {'2Types':0, 'Attchd':1, 'Basment':2, 'BuiltIn':3, 'CarPort':4, 'Detchd':5, 'No Garage':6}
    
    MSZoning = MSZ[MSZoning]
    Utilities = Utili[Utilities]
    Neighborhood = ngb_lblEval[Neighborhood]
    GarageType = grgtype[GarageType]
    HouseStyle = Hstyle[HouseStyle]
    prd_lis = [OverallQual, TotalBsmtSF, GrLivArea, MSZoning, Utilities, Neighborhood, GarageType, HouseStyle]
    prediction = model.predict([prd_lis])
    
    return (prediction[0])

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 1095)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1131, 1091))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/rithvik/House_pricing/Final_Files/House_Picture.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 0, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(28)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        #font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 130, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 281, 181))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(840, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        #font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(850, 130, 121, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(820, 180, 291, 91))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 80, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(370, 130, 290, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 360, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(40, 390, 121, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(10, 440, 461, 241))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setScaledContents(False)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(400, 180, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        #font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(430, 240, 121, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(390, 290, 321, 91))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(830, 360, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        #font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(850, 390, 121, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(775, 430, 340, 251))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 720, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(630, 720, 371, 41))#
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(180, 760, 91, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(810, 760, 91, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 840, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(160, 920, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.pressed)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "HOUSE PRICE PREDICTION"))
        self.label_3.setText(_translate("MainWindow", "Choose Zone"))
        self.label_3.adjustSize()#
        self.comboBox.setItemText(0, _translate("MainWindow", "C (all)"))
        self.comboBox.setItemText(1, _translate("MainWindow", "FV"))
        self.comboBox.setItemText(2, _translate("MainWindow", "RH"))
        self.comboBox.setItemText(3, _translate("MainWindow", "RL"))
        self.comboBox.setItemText(4, _translate("MainWindow", "RM"))
        self.label_4.setText(_translate("MainWindow", "ZONE INFORMATION\n"
"\n"
"C (all): Commercial\n"
"FV: Floating Village Residential\n"
"RH: Residential High Density\n"
"RL: Residential Low Density\n"
"RM: Residential Medium Density"))
        self.label_5.setText(_translate("MainWindow", "Choose Utilities"))
        self.label_5.adjustSize()#
        self.comboBox_2.setItemText(0, _translate("MainWindow", "AllPub"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "NoSeWa"))
        self.label_6.setText(_translate("MainWindow", "UTILITY INFORMATION\n"
"\n"
"AllPub: All public Utilities\n"
"NoSeWa: Electricity and Gas Only"))
        self.label_7.setText(_translate("MainWindow", "Choose Neighborhood"))
        self.label_7.adjustSize()#
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Bloomington Heights"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Bluestem"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Briardale"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Brookside"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Clear Creek"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "College Creek"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Crawford"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Edwards"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Gilbert"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "Iowa DOT and Rail Road"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "Meadow Village"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "Mitchell"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "North Ames"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "Northridge"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "Northpark Villa"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "Northridge Heights"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "Northwest Ames"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "Old Town"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "South & West of Iowa State University"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "Sawyer"))
        self.comboBox_3.setItemText(20, _translate("MainWindow", "Sawyer West"))
        self.comboBox_3.setItemText(21, _translate("MainWindow", "Somerset"))
        self.comboBox_3.setItemText(22, _translate("MainWindow", "Stone Brook"))
        self.comboBox_3.setItemText(23, _translate("MainWindow", "Timberland"))
        self.comboBox_3.setItemText(24, _translate("MainWindow", "Veenker"))
        self.label_8.setText(_translate("MainWindow", "Choose House Style"))
        self.label_8.adjustSize()#
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1Story"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "1.5Fin"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "1.5Unf"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "2Story"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "2.5Fin"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "2.5Unf"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "SFoyer"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "SLvl"))
        self.label_9.setText(_translate("MainWindow", "HOUSE STYLE INFORMATION\n"
"\n"
"1Story:    One story\n"
"1.5Fin:    One and one-half story: 2nd level finished\n"
"1.5Unf:    One and one-half story: 2nd level unfinished\n"
"2Story:    Two story\n"
"2.5Fin:    Two and one-half story: 2nd level finished\n"
"2.5Unf:    Two and one-half story: 2nd level unfinished\n"
"SFoyer:    Split Foyer\n"
"SLvl:    Split Level"))
        self.label_10.setText(_translate("MainWindow", "Choose House Quality  "))
        self.label_10.adjustSize()#
        self.comboBox_5.setItemText(0, _translate("MainWindow", "10"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "9"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "8"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "7"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "6"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "4"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "3"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "2"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "1"))
        self.label_11.setText(_translate("MainWindow", "QUALITY INFORMATION\n"
"\n"
"The higher quality you choose\n"
"the rate of house will increase"))
        self.label_12.setText(_translate("MainWindow", "Choose Garage Type"))
        self.label_12.adjustSize()#
        self.comboBox_6.setItemText(0, _translate("MainWindow", "2Types"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Attchd"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Basment"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "BuiltIn"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "CarPort"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "Detchd"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "No Garage"))
        self.label_13.setText(_translate("MainWindow", "GARAGE TYPE INFORMATION\n"
"\n"
"2Types:   More than one type of garage\n"
"Attchd:   Attached to home\n"
"Basment:   Basement Garage\n"
"BuiltIn:   Built-In (Garage part of house\n"
" - typically has room above garage)\n"
"CarPort:   Car Port\n"
"Detchd:  Detached from home"))
        self.label_14.setText(_translate("MainWindow", "Enter Total basement area in square feet[100 - 3000]"))
        self.label_14.adjustSize()
        self.label_15.setText(_translate("MainWindow", "Enter Ground living area in square feet[100 - 4000]"))
        self.label_15.adjustSize()
        self.pushButton.setText(_translate("MainWindow", "Estimate Price"))
        self.label_16.setText(_translate("MainWindow", ""))
    def pressed(self):
        Neighborhood = self.comboBox_3.currentText()
        HouseStyle = self.comboBox_4.currentText()
        MSZoning = self.comboBox.currentText()
        GrLivArea = (self.plainTextEdit_2.toPlainText()).strip()
        TotalBsmtSF = (self.plainTextEdit.toPlainText()).strip()
        GarageType = self.comboBox_6.currentText()
        OverallQual = self.comboBox_5.currentText()
        Utilities = self.comboBox_2.currentText()
        try:
            ans = get_prediction(Neighborhood, HouseStyle, MSZoning, int(GrLivArea), int(TotalBsmtSF), GarageType, int(OverallQual), Utilities)
            ans_len = len(str(ans).split('.')[0])
            #print(ans_len, ans)
            if ans_len >= 6:
                self.label_16.setText(' '*13 + "Estimated Price : $"+ str(ans)[:ans_len-6+3]+','+str(ans)[ans_len-6+3:ans_len-6+6])
                self.label_16.adjustSize()
            elif ans_len >=5 and ans_len < 6:
                self.label_16.setText(' '*13 + "Estimated Price : $"+ str(ans)[:ans_len-5+2]+','+str(ans)[ans_len-5+2:ans_len-5+5])
                self.label_16.adjustSize()
            else: 
                self.label_16.setText(' '*13 + "Estimated Price : $"+ '{:.0f}'.format(ans))
                self.label_16.adjustSize()
        except:
            self.label_16.setText(' '*21 + "Invalid Entry Try Again")
            self.label_16.adjustSize()
     

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
